services:
  - type: web
    name: SmartyMS-Uploader
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: AUTH_USERS
        sync: false
      - key: PORT
        value: 8000
